version: "3.8"
name: music_api-mariadb
services:
  mariadb:
    image: mariadb:11.2.6
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${MARIADB_PORT}:${MARIADB_DEFAULT_PORT}"
    volumes:
      - music_data:/var/lib/mysql
    networks:
      - networks-music

  app:
    image: mandrescasabon/music-api:latest
    container_name: music_api
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mariadb://${MARIADB_HOST}:${MARIADB_DEFAULT_PORT}/${MARIADB_DATABASE}",
        "spring.datasource.username" : "${MARIADB_USER}",
        "spring.datasource.password" : "${MARIADB_PASSWORD}",
        "spring.datasource.driverClassName" : "org.mariadb.jdbc.Driver",
        "spring.jpa.properties.hibernate.globally_quoted_identifiers" : true,
        "spring.jpa.hibernate.ddl-auto" : "update",
        "server.port" : "8080"
      }'
    depends_on:
      - mariadb
    restart: always
    networks:
      - networks-music

networks:
  networks-music:
    driver: bridge

volumes:
  music_data:
